MediaBundle/DependencyInjection/OpenOrchestraMediaExtension.php

https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/18
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/844
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/55
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/333
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/9

Replace deprecated method definition->setFactory*

---

MediaBundle/Document/Folder.php
MediaBundle/Repository/FolderRepository.php
MediaBundle/Tests/Document/FolderTest.php

@juchi this fix the folder search

folder list : also include folder not related to a site

---

Media/Model/FolderInterface.php
MediaBundle/Document/Folder.php

fix folder save

---

Media/DisplayBlock/Strategies/CarrouselStrategy.php
MediaBundle/DependencyInjection/OpenOrchestraMediaExtension.php
MediaBundle/Resources/public/block/Carrousel/blockLoader.js
MediaBundle/Resources/views/Block/Carrousel/show.html.twig

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/930
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/68

Use blockLoader + fix broken BO

---

MediaModelBundle/DataFixtures/MongoDB/LoadFolderData.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/379
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/72
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/28
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/947

remove site 1 fixture

---

Media/DisplayBlock/Strategies/GalleryStrategy.php
Media/DisplayBlock/Strategies/MediaListByKeywordStrategy.php

https://github.com/open-orchestra/open-orchestra-media-bundle/pull/74
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/162
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/112
https://github.com/open-orchestra/open-orchestra-docs/pull/68

rename getTags to getCacheTags

---

MediaBundle/Resources/views/Block/Gallery/show.html.twig
MediaBundle/Resources/views/Block/Slideshow/show.html.twig

https://github.com/open-orchestra/open-orchestra-display-bundle/pull/167
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/81

fix require js and css multi bloc

---

Media/DisplayBlock/Strategies/GalleryStrategy.php
MediaBundle/Resources/public/block/Gallery/blockLoader.js
MediaBundle/Resources/views/Block/Gallery/show.html.twig

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/20
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/89

add_width_gallery

---

composer.json

Reverts open-orchestra/open-orchestra-media-bundle#96

Revert "update mongo odm"

---

MediaModelBundle/DataFixtures/MongoDB/LoadFolderData.php
MediaModelBundle/DataFixtures/MongoDB/LoadMediaData.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/428
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/108

Add reference to logo fixture

---

Media/DisplayMedia/Strategies/AbstractStrategy.php
Media/DisplayMedia/Strategies/ImageStrategy.php
MediaBundle/Tests/DisplayMedia/Strategies/AbstractStrategyTest.php

https://github.com/open-orchestra/open-orchestra-media-bundle/pull/117
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/36

Remove tinymce format selection for non image media

---

Media/DisplayMedia/Strategies/AbstractStrategy.php
Media/DisplayMedia/Strategies/AudioStrategy.php
Media/Thumbnail/Strategies/VideoToImageManager.php
MediaBundle/Resources/config/display.yml
MediaBundle/Resources/translations/messages.en.yml
MediaBundle/Resources/translations/messages.fr.yml
MediaBundle/Resources/views/BBcode/front_audio.html.twig
MediaBundle/Resources/views/BBcode/wysiwyg_audio.html.twig
MediaBundle/Tests/DisplayMedia/Strategies/AbstractStrategyTest.php
MediaBundle/Tests/DisplayMedia/Strategies/AudioStrategyTest.php

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/45
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/126

1 0 audio media

---

Media/DisplayMedia/Strategies/AbstractStrategy.php
Media/DisplayMedia/Strategies/AudioStrategy.php
Media/Thumbnail/Strategies/VideoToImageManager.php
MediaBundle/Resources/config/display.yml
MediaBundle/Resources/translations/messages.en.yml
MediaBundle/Resources/translations/messages.fr.yml
MediaBundle/Resources/views/BBcode/front_audio.html.twig
MediaBundle/Resources/views/BBcode/wysiwyg_audio.html.twig
MediaBundle/Tests/DisplayMedia/Strategies/AbstractStrategyTest.php
MediaBundle/Tests/DisplayMedia/Strategies/AudioStrategyTest.php

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/47
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/127

Create AudioStrategy to display audio media

---

Media/Manager/SaveMediaManager.php
Media/Manager/SaveMediaManagerInterface.php
MediaBundle/Tests/Manager/SaveMediaManagerTest.php
MediaModelBundle/DependencyInjection/OpenOrchestraMediaModelExtension.php
MediaModelBundle/Manager/MediaManager.php
MediaModelBundle/Manager/MediaManagerInterface.php
MediaModelBundle/Resources/config/manager.yml
MediaModelBundle/Resources/config/resolve_document.yml

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/66
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/134
https://github.com/open-orchestra/open-orchestra/pull/706
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/83

Remove multi-save on SaveMediaManager

---

MediaBundle/DependencyInjection/CompilerPass/TwigGlobalsCompilerPass.php
MediaBundle/DependencyInjection/OpenOrchestraMediaExtension.php
MediaBundle/OpenOrchestraMediaBundle.php
MediaBundle/Resources/config/manager.yml
MediaBundle/Resources/config/mime_type.yml

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/87
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/137

Add allowed mime types

---

MediaBundle/DependencyInjection/Configuration.php
MediaBundle/DependencyInjection/OpenOrchestraMediaExtension.php
MediaBundle/Tests/DependencyInjection/Fixtures/config/value.yml
MediaBundle/Tests/DependencyInjection/OpenOrchestraMediaExtensionTest.php
MediaModelBundle/DataFixtures/MongoDB/LoadMediaData.php

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/97
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/141
https://github.com/open-orchestra/open-orchestra-media-file-bundle/pull/4
https://github.com/open-orchestra/open-orchestra-media-demo/pull/37
https://github.com/open-orchestra/open-orchestra-front-demo/pull/144

1.1 : refacto upload 

---

composer.json

https://travis-ci.org/open-orchestra/open-orchestra/jobs/99072026

fix doctrine cache requirement php5.5

---

Media/Tests/BBcode/AbstractMediaCodeDefinitionTest.php
Media/Tests/BBcode/MediaBundleBBcodeCollectionTest.php
Media/Tests/BBcode/MediaCodeDefinitionTest.php
Media/Tests/BBcode/MediaWithoutFormatCodeDefinitionTest.php
Media/Tests/DisplayMedia/DisplayMediaManagerTest.php
Media/Tests/DisplayMedia/Strategies/AbstractStrategyTest.php
Media/Tests/DisplayMedia/Strategies/AudioStrategyTest.php
Media/Tests/Twig/DisplayMediaExtensionTest.php
MediaBundle/Tests/DependencyInjection/OpenOrchestraMediaExtensionTest.php
MediaModelBundle/Tests/DependencyInjection/OpenOrchestraMediaModelExtensionTest.php
MediaModelBundle/Tests/Document/FolderTest.php
MediaModelBundle/Tests/Model/EntityTest.php

https://github.com/open-orchestra/open-orchestra-libs/pull/38
https://github.com/open-orchestra/open-orchestra-media-file-bundle/pull/6
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/66
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/11
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1340
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/116
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/154
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/83
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/86
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/504
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/191 …

Clean up tear down test

---

Media/DisplayMedia/Strategies/AbstractStrategy.php
Media/DisplayMedia/Strategies/ImageStrategy.php
MediaModelBundle/DependencyInjection/OpenOrchestraMediaModelExtension.php
MediaModelBundle/Document/Folder.php
MediaModelBundle/Document/Media.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1342
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/117
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/156

Add new name to alternative file

---

MediaModelBundle/DependencyInjection/Compiler/EntityResolverCompilerPass.php

https://github.com/open-orchestra/open-orchestra-base-api-mongo-model-bundle/pull/15
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1383
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/157
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/515
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/85
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/88

supress deprecated

---

Media/DisplayBlock/Strategies/DisplayMediaStrategy.php
Media/DisplayBlock/Strategies/GalleryStrategy.php
Media/DisplayBlock/Strategies/MediaListByKeywordStrategy.php
Media/DisplayBlock/Strategies/SlideshowStrategy.php
MediaBundle/DependencyInjection/OpenOrchestraMediaExtension.php

[OO-MISC] Refacto const display strategies name
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/518
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/194
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/140
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/162
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1407

Rename strategies name

---

Media/DisplayBlock/Strategies/GalleryStrategy.php
Media/DisplayBlock/Strategies/SlideshowStrategy.php
Media/Tests/Twig/DisplayMediaExtensionTest.php
Media/Twig/DisplayMediaExtension.php
MediaBundle/Resources/config/twig.yml
MediaBundle/Resources/views/Block/DisplayMedia/show.html.twig
MediaBundle/Resources/views/Block/Gallery/show.html.twig
MediaBundle/Resources/views/Block/Slideshow/show.html.twig

Refacto oo-media-choice-type
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/173
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/172

1 1 refacto media choice type

---

Media/Model/MediaInterface.php
Media/Repository/MediaRepositoryInterface.php
MediaModelBundle/Document/Media.php
MediaModelBundle/Repository/MediaRepository.php

[OO-FEATURE] Media can be filtered on type when displayed from media folder
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/179
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/175

1.1 filter media modal

---

Media/DisplayMedia/Strategies/AbstractStrategy.php
Media/DisplayMedia/Strategies/ImageStrategy.php

https://github.com/open-orchestra/open-orchestra-front-bundle/pull/150
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/179

fix requestStack

---

Media/DisplayBlock/Strategies/GalleryStrategy.php
Media/DisplayBlock/Strategies/MediaListByKeywordStrategy.php
Media/DisplayBlock/Strategies/SlideshowStrategy.php
Media/Model/MediaInterface.php
Media/Tests/Twig/DisplayMediaExtensionTest.php
Media/Twig/DisplayMediaExtension.php

[OO-MISC] Remove MediaInterface::MEDIA_PREFIX
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/198
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/180

Remove MEDIA_PREFIX usage

---

composer.json

[OO-BUGFIX] Fix dependency ``doctrine/mongodb-odm-bundle``

Fix mongo dependency

---

composer.json

[OO-BUGFIX] Fix the dependencies on OO dev bundles

Fix oo dependencies in 1.0.x-dev

---

MediaModelBundle/Resources/config/validation.yml

[OO-BUGFIX] fix fix the document folder validator

fix the document folder validator

---

Media/DisplayMedia/DisplayMediaManager.php

[OO-BUGFIX] custom styles are correctly used in displayMedia

Fix displayMedia style

---

Media/DisplayBlock/Strategies/MediaListByKeywordStrategy.php
MediaModelBundle/Repository/MediaRepository.php

[OO-FEATURE] stock reference keyword
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1734
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/232
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/583
https://github.com/open-orchestra/open-orchestra-model-interface/pull/188
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/31
https://github.com/open-orchestra/open-orchestra-libs/pull/51
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/219
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/201
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/35

add reference for keywordable entity

---

MediaBundle/Resources/config/bbcode.yml
MediaBundle/Resources/config/display.yml
MediaBundle/Resources/config/display_block.yml
MediaBundle/Resources/config/twig.yml
MediaModelBundle/Resources/config/resolve_document.yml

[OO-FEATURE] Adding yaml compatibility for Symfony 3

add compatibility yaml symfony 3.0

---

Media/Model/MediaInterface.php
MediaModelBundle/Document/Media.php

[OO-MISC] Update phpdoc MediaInterface

fix collection phpdoc

---

composer.json

[OO-MISC] Update some vendor versions
https://github.com/open-orchestra/open-orchestra/pull/986
https://github.com/open-orchestra/open-orchestra-media-demo/pull/117
https://github.com/open-orchestra/open-orchestra-front-demo/pull/252
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/139
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/612
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/222
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/266
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/49
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1795
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/105

Remove doctrine/data-fixtures

---

Media/Model/MediaInterface.php
MediaModelBundle/Document/Media.php

[OO-FEATURE] Add possibility to add informations like exif data in the media documents.
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/273
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/228

add property media information

---

MediaModelBundle/Document/Folder.php

[OO-FEATURE] Add index folder document

add index folder document

---

MediaModelBundle/Document/Folder.php

[OO-FEATURE] Add index folder document
cherry-pick https://github.com/open-orchestra/open-orchestra-media-bundle/pull/229

add index folder document (#229)

---

Media/Model/MediaInterface.php
MediaModelBundle/Document/Media.php
MediaModelBundle/Migrations/MongoDB/Version20160831150310.php

[OO-FEATURES] Improvement of translation storage
[OO-MISC] Add migration ``20160831150650`` to update translation storage of medias
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/145
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/232
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/280
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/48
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/638
https://github.com/open-orchestra/open-orchestra-model-interface/pull/220
https://github.com/open-orchestra/open-orchestra/pull/1025
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1858

update translation storage

---

Media/Model/MediaInterface.php
Media/Repository/MediaRepositoryInterface.php
MediaModelBundle/Document/Media.php
MediaModelBundle/Repository/MediaRepository.php

[OO-FEATURE] Add use tracking to keywords
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/50
https://github.com/open-orchestra/open-orchestra-model-interface/pull/225
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/643
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/233
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/282
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1862
https://github.com/open-orchestra/open-orchestra-bbcode-bundle/pull/25
https://github.com/open-orchestra/open-orchestra/pull/1027

1.2 keyword references

---

Media/Repository/FolderRepositoryInterface.php
MediaModelBundle/Repository/FolderRepository.php

https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/52
https://github.com/open-orchestra/open-orchestra-model-interface/pull/231
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/650
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/235
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/56
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1890
https://github.com/open-orchestra/open-orchestra-libs/pull/64

update deprecated annotation

---

MediaModelBundle/Resources/config/validation.yml

https://github.com/open-orchestra/open-orchestra-media-bundle/pull/236
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/300

add group upload file constraint

---

MediaModelBundle/Resources/config/validation.yml

cherry pick  https://github.com/open-orchestra/open-orchestra-media-bundle/pull/236
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/237
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/303

add group upload file constraint (#236)

---

Media/BBcode/AbstractMediaCodeDefinition.php
Media/DisplayMedia/DisplayMediaInterface.php
Media/DisplayMedia/DisplayMediaManager.php
Media/DisplayMedia/Strategies/AbstractStrategy.php
Media/DisplayMedia/Strategies/AudioStrategy.php
Media/DisplayMedia/Strategies/DefaultStrategy.php
Media/DisplayMedia/Strategies/ImageStrategy.php
Media/DisplayMedia/Strategies/PdfStrategy.php
Media/DisplayMedia/Strategies/VideoStrategy.php
Media/Repository/FolderRepositoryInterface.php
Media/Tests/BBcode/AbstractMediaCodeDefinitionTest.php
Media/Tests/Twig/DisplayMediaExtensionTest.php
Media/Twig/DisplayMediaExtension.php
MediaModelBundle/Repository/FolderRepository.php

[OO-SUPPRESSED] Method DisplayMediaInterface::displayMedia
[OO-SUPPRESSED] Method DisplayMediaManager::displayMedia
[OO-SUPPRESSED] Method AbstractStrategy::displayMedia
[OO-SUPPRESSED] Method AudioStrategy::displayMedia
[OO-SUPPRESSED] Method DefaultStrategy::displayMedia
[OO-SUPPRESSED] Method ImageStrategy::displayMedia
[OO-SUPPRESSED] Method PdfStrategy::displayMedia
[OO-SUPPRESSED] Method VideoStrategy::displayMedia
[OO-SUPPRESSED] Method FolderRepositoryInterface::findAllRootFolder
[OO-SUPPRESSED] Twig extension display_media
[OO-SUPPRESSED] Method FolderRepository::findAllRootFolder
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/61
https://github.com/open-orchestra/open-orchestra-model-interface/pull/244
https://github.com/open-orchestra/open-orchestra-model-bundle …

remove deprecated

---

Media/Model/FolderInterface.php
Media/Model/MediaFolderInterface.php
MediaModelBundle/Document/Folder.php

[OO-FEATURE] Refacto the right layer
https://github.com/open-orchestra/open-orchestra/pull/1087
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/1997
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/322
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/240
https://github.com/open-orchestra/open-orchestra-model-interface/pull/256
https://github.com/open-orchestra/open-orchestra-workflow-function-bundle/pull/156
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/113

2 0 refacto rights

---

Media/Model/FolderInterface.php
Media/Model/MediaFolderInterface.php
MediaModelBundle/DependencyInjection/OpenOrchestraMediaModelExtension.php
MediaModelBundle/Document/Folder.php
MediaModelBundle/Document/MediaFolder.php
MediaModelBundle/EventListener/GeneratePathListener.php
MediaModelBundle/Repository/FolderRepository.php
MediaModelBundle/Resources/config/listener.yml
MediaModelBundle/Tests/EventListener/GeneratePathListenerTest.php

[OO-FEATURE] Add media folder path

2 0 media path

---

Media/Model/FolderInterface.php

https://github.com/open-orchestra/open-orchestra-model-bundle/pull/706
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/137
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/243
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/332
https://github.com/open-orchestra/open-orchestra/pull/1114
https://github.com/open-orchestra/open-orchestra-model-interface/pull/267
https://github.com/open-orchestra/open-orchestra-model-interface/pull/267

remove role, workflowfunction and worklow right

---

Media/DisplayBlock/Strategies/DisplayMediaStrategy.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2086
https://github.com/open-orchestra/open-orchestra-model-interface/pull/285
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/728
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/64
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/245
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/250
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/69
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/209

remove currently version

---

Media/Repository/MediaRepositoryInterface.php
MediaModelBundle/DependencyInjection/OpenOrchestraMediaModelExtension.php
MediaModelBundle/Repository/FolderRepository.php
MediaModelBundle/Repository/MediaRepository.php

[OO-FEATURE] Add media list
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/339
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/244
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2085
https://github.com/open-orchestra/open-orchestra/pull/1139

2 0 media list

---

Media/Repository/FolderRepositoryInterface.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2094
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/247
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/343

add method in interface to refresh test

---

Media/DisplayMedia/Strategies/AbstractStrategy.php
Media/DisplayMedia/Strategies/ImageStrategy.php
Media/Model/MediaInterface.php
Media/Tests/DisplayMedia/Strategies/AbstractStrategyTest.php
Media/Tests/DisplayMedia/Strategies/ImageStrategyTest.php
Media/Tests/Twig/DisplayMediaExtensionTest.php
Media/Twig/DisplayMediaExtension.php
MediaModelBundle/Document/Media.php

[OO-FEATURE] Add media edit view
https://github.com/open-orchestra/open-orchestra/pull/1145
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2097
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/344
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/248
https://github.com/open-orchestra/open-orchestra-media-file-bundle/pull/31

2 0 media edit

---

Media/BBcode/AbstractMediaCodeDefinition.php
Media/DisplayMedia/DisplayMediaInterface.php
Media/DisplayMedia/DisplayMediaManager.php
Media/DisplayMedia/Strategies/AbstractStrategy.php
Media/DisplayMedia/Strategies/AudioStrategy.php
Media/DisplayMedia/Strategies/ImageStrategy.php
Media/Tests/BBcode/AbstractMediaCodeDefinitionTest.php
Media/Tests/BBcode/MediaWithoutFormatCodeDefinitionTest.php
Media/Tests/DisplayMedia/DisplayMediaManagerTest.php
Media/Tests/DisplayMedia/Strategies/AbstractStrategyTest.php
Media/Tests/DisplayMedia/Strategies/AudioStrategyTest.php
Media/Tests/DisplayMedia/Strategies/ImageStrategyTest.php
MediaBundle/Resources/views/BBcode/WysiwygDisplay/audio.html.twig
MediaBundle/Resources/views/BBcode/WysiwygDisplay/image.html.twig
MediaBundle/Resources/views/BBcode/WysiwygDisplay/thumbnail.html.twig

[OO-FEATURE] Media in tinymce
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2129
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/350
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/251

2 0 tinymce media

---

Media/Repository/FolderRepositoryInterface.php
MediaModelBundle/Repository/FolderRepository.php

[OO-FEATURE] Add folder list view
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2090
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/246
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/342

Remove unset by reference

---

Media/DisplayBlock/Strategies/DisplayMediaStrategy.php
Media/DisplayBlock/Strategies/GalleryStrategy.php
Media/DisplayBlock/Strategies/MediaListByKeywordStrategy.php
Media/DisplayBlock/Strategies/SlideshowStrategy.php
Media/DisplayMedia/Strategies/AbstractDisplayMediaStrategy.php
Media/DisplayMedia/Strategies/AudioStrategy.php
Media/DisplayMedia/Strategies/DefaultStrategy.php
Media/DisplayMedia/Strategies/ImageStrategy.php
Media/DisplayMedia/Strategies/PdfStrategy.php
Media/DisplayMedia/Strategies/VideoStrategy.php
Media/Tests/DisplayMedia/Strategies/AbstractDisplayMediaStrategyTest.php
Media/Tests/DisplayMedia/Strategies/AudioStrategyTest.php
Media/Tests/DisplayMedia/Strategies/DefaultStrategyTest.php
Media/Tests/DisplayMedia/Strategies/ImageStrategyTest.php
Media/Tests/DisplayMedia/Strategies/PdfStrategyTest.php
Media/Tests/DisplayMedia/Strategies/VideoStrategyTest.php

[OO-REFACTO] Rename Abstract Stratgies
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/118
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2148
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/254
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/68
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/252
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/142

Rename Abstract Strategies

---

MediaBundle/DependencyInjection/OpenOrchestraMediaExtension.php
MediaBundle/Resources/views/BBcode/WysiwygDisplay/audio.html.twig
MediaBundle/Resources/views/BBcode/media_not_found.html.twig

[OO-MISC] Remove assetic
https://github.com/open-orchestra/open-orchestra/pull/1163
https://github.com/open-orchestra/open-orchestra-base-bundle/pull/123
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2149
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/253

Remove assetic

---

Media/Repository/FolderRepositoryInterface.php
Media/Repository/MediaRepositoryInterface.php
MediaModelBundle/Repository/FolderRepository.php
MediaModelBundle/Repository/MediaRepository.php

https://github.com/open-orchestra/open-orchestra/pull/1166
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/363
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/751
https://github.com/open-orchestra/open-orchestra-user-bundle/pull/143
https://github.com/open-orchestra/open-orchestra-mongo-libs/pull/74
https://github.com/open-orchestra/open-orchestra-model-interface/pull/297
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/254
https://github.com/open-orchestra/open-orchestra-libs/pull/76
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2165
https://github.com/open-orchestra/open-orchestra-base-api-mongo-model-bundle/pull/34
https://github.com/open-orchestra/open-orchestra-base-api-bundle/pull/119

remove useless code

---

Media/Model/MediaInterface.php
Media/Model/MediaLibrarySharingInterface.php
Media/Repository/MediaLibrarySharingRepositoryInterface.php
Media/Repository/MediaRepositoryInterface.php
MediaModelBundle/DependencyInjection/Configuration.php
MediaModelBundle/Document/Media.php
MediaModelBundle/Document/MediaLibrarySharing.php
MediaModelBundle/Repository/MediaLibrarySharingRepository.php
MediaModelBundle/Repository/MediaRepository.php
MediaModelBundle/Resources/config/resolve_document.yml
MediaModelBundle/Tests/Model/EntityTest.php

https://github.com/open-orchestra/open-orchestra-media-bundle/pull/256
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/757
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/367
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2189
https://github.com/open-orchestra/open-orchestra/pull/1171
https://github.com/open-orchestra/open-orchestra-model-interface/pull/301

add media share site

---

Media/DisplayMedia/DisplayMediaInterface.php
Media/DisplayMedia/DisplayMediaManager.php
Media/DisplayMedia/Strategies/AbstractDisplayMediaStrategy.php
Media/DisplayMedia/Strategies/VideoStrategy.php
Media/Exception/BadFileException.php
Media/Manager/MediaStorageManager.php
Media/Manager/MediaStorageManagerInterface.php
Media/Tests/DisplayMedia/DisplayMediaManagerTest.php
Media/Tests/DisplayMedia/Strategies/AbstractDisplayMediaStrategyTest.php
Media/Tests/DisplayMedia/Strategies/AudioStrategyTest.php
Media/Tests/DisplayMedia/Strategies/DefaultStrategyTest.php
Media/Tests/DisplayMedia/Strategies/ImageStrategyTest.php
Media/Tests/DisplayMedia/Strategies/PdfStrategyTest.php
Media/Tests/DisplayMedia/Strategies/VideoStrategyTest.php
Media/Tests/Manager/MediaStorageManagerTest.php
Media/Tests/Twig/DisplayMediaExtensionTest.php
Media/Twig/DisplayMediaExtension.php
MediaBundle/DependencyInjection/Configuration.php
MediaBundle/DependencyInjection/OpenOrchestraMediaExtension.php
MediaBundle/Resources/config/display.yml
MediaBundle/Resources/config/manager.yml

[OO-BCBREAK] Remove gaufrette
[OO-BCBREAK] Remove mediaFileBundle
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/257
https://github.com/open-orchestra/open-orchestra/pull/1181
https://github.com/open-orchestra/open-orchestra-front-demo/pull/350
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/373
https://github.com/open-orchestra/open-orchestra-provision-docker/pull/4

remove application media

---

Media/Repository/MediaRepositoryInterface.php
MediaModelBundle/Repository/FolderRepository.php
MediaModelBundle/Repository/MediaRepository.php

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/378
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/258

Add perimeter search on MediaRepository::filterSearch

---

Media/Model/MediaFolderInterface.php
Media/Repository/MediaRepositoryInterface.php
MediaModelBundle/Document/Media.php
MediaModelBundle/Document/MediaFolder.php
MediaModelBundle/Repository/MediaRepository.php

https://github.com/open-orchestra/open-orchestra/pull/1198
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/262
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/385

remove medias from folder

---

Media/Repository/FolderRepositoryInterface.php
Media/Repository/MediaRepositoryInterface.php
MediaModelBundle/Repository/FolderRepository.php
MediaModelBundle/Repository/MediaRepository.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2249
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/260
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/382
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/766
https://github.com/open-orchestra/open-orchestra-model-interface/pull/306

Add command delete site

---

Media/Repository/FolderRepositoryInterface.php
MediaModelBundle/Repository/FolderRepository.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2279
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/392
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/263

Add FolderRepository::countChildren

---

Media/Repository/MediaRepositoryInterface.php
MediaModelBundle/Repository/MediaRepository.php

https://github.com/open-orchestra/open-orchestra/pull/1216
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/266
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/398

add method media of

---

Media/Model/FolderInterface.php
MediaModelBundle/Document/Folder.php
MediaModelBundle/Document/MediaFolder.php
MediaModelBundle/Resources/config/validation.yml

https://github.com/open-orchestra/open-orchestra/pull/1217
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/400
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/267
https://github.com/open-orchestra/open-orchestra-migration-bundle/pull/20
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/774

Internationalize folder name

---

Media/DisplayBlock/Strategies/DisplayMediaStrategy.php

https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/406
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2322
https://github.com/open-orchestra/open-orchestra/pull/1221
https://github.com/open-orchestra/open-orchestra-front-bundle/pull/226
https://github.com/open-orchestra/open-orchestra-elastica-bundle/pull/75
https://github.com/open-orchestra/open-orchestra-display-bundle/pull/264
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/268

Refacto context manager

---

MediaBundle/DependencyInjection/OpenOrchestraMediaExtension.php
MediaModelBundle/Document/MediaFolder.php

https://github.com/open-orchestra/open-orchestra-media-bundle/pull/269
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/409
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/776
https://github.com/open-orchestra/open-orchestra-elastica-admin-bundle/pull/2

remove block media keywords

---

MediaModelBundle/DependencyInjection/OpenOrchestraMediaModelExtension.php
MediaModelBundle/Form/Type/Component/FolderChoiceType.php
MediaModelBundle/Repository/FolderRepository.php
MediaModelBundle/Resources/config/form.yml
MediaModelBundle/Tests/Form/Type/Component/FolderChoiceTypeTest.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2329
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/408
https://github.com/open-orchestra/open-orchestra/pull/1222
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/270

add test on repository folder

---

Media/Form/Type/Component/AbstractFolderChoiceType.php
MediaModelBundle/Form/Type/Component/FolderChoiceType.php
MediaModelBundle/Resources/config/form.yml
MediaModelBundle/Tests/Form/Type/Component/FolderChoiceTypeTest.php

https://github.com/open-orchestra/open-orchestra-media-bundle/pull/271
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/412
https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2332

fix test and dependency

---

Media/Repository/FolderRepositoryInterface.php
MediaModelBundle/Repository/FolderRepository.php

https://github.com/open-orchestra/open-orchestra-cms-bundle/pull/2346
https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/420
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/273
https://github.com/open-orchestra/open-orchestra-model-bundle/pull/781
https://github.com/open-orchestra/open-orchestra-model-interface/pull/315
https://github.com/open-orchestra/open-orchestra/pull/1233

suppress recursive path
